---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: box-cutter/ubuntu1404-desktop

suites:
  - name: default
    run_list:
      - recipe[basic-lemr-stack::default]
    attributes:
