name 'basic-lemr-stack'
maintainer 'Matt Stratton'
maintainer_email 'mattstratton@chef.io'
license 'all_rights'
description 'Installs/Configures basic-lemr-stack'
long_description 'Installs/Configures basic-lemr-stack'
version '0.1.0'

depends 'rbenv', '~> 1.7.1'
depends 'nginx', '~> 2.7.6'
depends 'mysql', '~> 6.1.0'
depends 'atom', '~> 0.1.1'
